before_script:
  - echo -e "machine git.cardinfolink.net\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - date

stages:
  - image_build

# 添加 docker_build stage
image_build:
  stage: image_build
  script:
    - echo "build docker image..."
    - echo "docker build -t $IMAGE -f Dockerfile ."
    - Date=`date +%Y%m%d%H%M%S`
    - IMAGE="harbor.xunliandata.com/evocloud/monstache"
    # - IMAGE_TAG="${CI_COMMIT_BRANCH:-$CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}"
    - if [ -z "${CI_COMMIT_BRANCH+x}" ]; then IMAGE_TAG="${CI_COMMIT_TAG}"
    - else IMAGE_TAG="${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
    - fi
    - echo $IMAGE_TAG
    - docker build -t $IMAGE:$IMAGE_TAG -f Dockerfile .
    - sh /var/run/scripts/deploy.sh $CI_PROJECT_NAME
    - echo "docker image $IMAGE:$IMAGE_TAG build ok..."
    - echo "IMAGE=$IMAGE" >> build.env
    - echo "IMAGE_TAG=$IMAGE_TAG" >> build.env
  tags:
    - image_build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never
    - exists:
        - Dockerfile
  artifacts:
    reports:
      dotenv: build.env

