mongo-url = "mongodb://10.30.11.112:27017,10.30.11.112:27018,10.30.11.112:27019"
namespace-regex = "db1.*"
namespace-drop-regex = ""
namespace-exclude-regex = ""
namespace-drop-exclude-regex = ""
enable-oplog = true
disable-change-events = false
disable-delete-protection = false
enable-easy-json = false
Stats = false
index-stats = false
stats-duration = ""
stats-index-format = ""
Gzip = false
Verbose = true
resume = true
resume-name = "checkpoint2"
resume-strategy = 0
resume-write-unsafe = false
resume-from-timestamp = 0
resume-from-earliest-timestamp = false
Replay = false
dropped-databases = false
dropped-collections = false
index-files = false
index-as-update = false
file-highlighting = false
disable-file-pipeline-put = false
enable-patches = false
fail-fast = false
merge-patch-attribute = ""
mapper-plugin-path = ""
enable-http-server = true
http-server-addr = ""
pipe-allow-disk = false
delete-strategy = 0
delete-index-pattern = ""
config-database-name = ""
file-downloaders = 0
relate-threads = 0
relate-buffer = 0
post-processors = 0
prune-invalid-json = false

[sink]
[sink.clickhouse]
enabled = true
endpoint = "http://10.30.11.112:8123"
endpoint-tcp = "10.30.11.112:9000"
skip-unknown-fields = true
date-time-best-effort = true
database = "evocloud"
table-prefix = "hk_"
table-suffix = "_v1"
[sink.clickhouse.auth]
user = "default"
password = ""