EnableTemplate = false
EnvDelimiter = ""
mongo-url = "mongodb://10.30.11.112:27017,10.30.11.112:27018,10.30.11.112:27019"
mongo-config-url = ""
mongo-oplog-database-name = ""
mongo-oplog-collection-name = ""
graylog-addr = ""
elasticsearch-user = ""
elasticsearch-password = ""
elasticsearch-pem-file = ""
elasticsearch-validate-pem-file = false
elasticsearch-version = ""
elasticsearch-healthcheck-timeout-startup = 0
elasticsearch-healthcheck-timeout = 0
elasticsearch-api-key = ""
namespace-regex = "db1.col1"
namespace-drop-regex = ""
namespace-exclude-regex = ""
namespace-drop-exclude-regex = ""
cluster-name = ""
print-config = false
Version = false
Pprof = false
enable-oplog = true
disable-change-events = false
disable-delete-protection = false
enable-easy-json = false
Stats = false
index-stats = false
stats-duration = ""
stats-index-format = ""
Gzip = false
Verbose = false
resume = true
resume-name = "checkpoint"
resume-strategy = 0
resume-write-unsafe = false
resume-from-timestamp = 0
resume-from-earliest-timestamp = false
Replay = false
dropped-databases = false
dropped-collections = false
index-files = false
index-as-update = false
file-highlighting = false
disable-file-pipeline-put = false
enable-patches = false
fail-fast = false
index-oplog-time = false
oplog-ts-field-name = ""
oplog-date-field-name = ""
oplog-date-field-format = ""
exit-after-direct-reads = false
merge-patch-attribute = ""
elasticsearch-max-conns = 0
elasticsearch-retry = false
elasticsearch-max-docs = 0
elasticsearch-max-bytes = 0
elasticsearch-max-seconds = 0
elasticsearch-client-timeout = 0
ElasticMajorVersion = 0
ElasticMinorVersion = 0
max-file-size = 0
ConfigFile = ""
Worker = ""
direct-read-split-max = 0
direct-read-concur = 0
direct-read-no-timeout = false
direct-read-bounded = false
direct-read-stateful = false
direct-read-dynamic-exclude-regex = ""
direct-read-dynamic-include-regex = ""
mapper-plugin-path = ""
enable-http-server = true
http-server-addr = ""
time-machine-index-prefix = ""
time-machine-index-suffix = ""
time-machine-direct-reads = false
pipe-allow-disk = false
delete-strategy = 0
delete-index-pattern = ""
config-database-name = ""
file-downloaders = 0
relate-threads = 0
relate-buffer = 0
post-processors = 0
prune-invalid-json = false
Debug = false
virtual-delete-field-name = "is_deleted"
kafka-brokers = "10.30.11.112:9092"
kafka-topic-prefix = "monstache."

[aws-connect]
  Strategy = 0
  access-key = ""
  secret-key = ""
  Region = ""
  Profile = ""
  credentials-file = ""
  credentials-watch-dir = ""
  watch-credentials = false
  force-expire = ""

[log-rotate]
  max-size = 0
  max-age = 0
  max-backups = 0
  localtime = false
  compress = false

[logs]
  Info = ""
  Warn = ""
  Error = ""
  Trace = ""
  Stats = ""

[elasticsearch-pki-auth]
  cert-file = ""
  key-file = ""
